### ISSUE TITLE
Ketchum To-Do's to get to beta

### ISSUE THREAD

**Issue by hathbanger** [versatus/versatus-ketchum#1]
This serves as an outline of things needed to get ketchum to betanet.

- [ ] Sort out underlying nft architecture (tokenMap)
- [ ] only allow for ownership of one instance in any one wallet of each pokemon
- [ ] ensure leveling works with new nft architecture
- [ ] determine training methods and platform
- [ ] determine battle methods and platform
- [ ] determine catch methods and platform
- [ ] determine betting methods
- [ ] create ws based service to facilitate peer to peer battles
- [ ] add moves to pokemon along with select ability of moves as they grow
- [ ] deploy pokemon dollars
- [ ] create marketplace with ability to sell and buy pokemon using pokemon dollars
- [ ] create pokeball nfts
- [ ] enable catch method through throwing of pokeball
